ManilaScience/config/routes.rb
Rails.application.routes.draw do

  resources :officers
  get 'class_courses/new_club' => 'class_courses#new_club'

  get 'class_lists/new_view' => 'class_lists#new_view'
  post 'class_lists/new_view' => 'class_lists#new_view'

  post 'class_lists/new_class_lists' => 'class_lists#new_class_lists'

  post 'class_view/view_class' => 'class_view#view_class'
  get 'class_view/view_class' => 'class_view#view_class'

  post 'club_view/view_club' => 'club_view#view_club'
  get 'club_view/view_club' => 'club_view#view_club'

  resources :messages
  resources :thread_message_tables
  resources :thread_messages
  get 'notifications/link_through'

  get 'class_courses/new_club' => 'class_courses#new_club'
  get 'notifications/read_post' => 'notifications#read_post'
  post 'notifications/read_post' => 'notifications#read_post'

  get 'posts/new' => 'posts#new'
  post 'posts/new' => 'posts#new'

  get 'posts/:id' => 'posts#show'
  post 'posts/:id' => 'posts#show'

  get 'posts/:id/edit' => 'posts#edit'
  post 'posts/:id/edit' => 'posts#edit'

  resources :announcements
  resources :posts
  resources :messages
  resources :groups
  resources :group_lists
  resources :posts
  resources :calendar_events

  resources :class_lists
  resources :class_courses
  resources :subjects
  resources :works_ins
  resources :departments
  resources :departments
  resources :employee_lists
  resources :teacher_lists
  resources :notifications
  devise_for :views

  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

  scope "/admin" do
    resources :users
  end

  resources :roles
  resources :users do
    collection { delete :destroy_multiple}
    collection { post :deletebybatch}
    collection { post :import}
    collection do
      delete 'destroy_multiple'
    end
  end

  get 'static/index'

  get 'class_view/index'
  get 'club_view/index'
  get 'group_view/index'
  get 'group_view/edit_student_lists'
  
  post 'group_view/add_user_from_group'
  post 'group_view/remove_user_from_group'

  get 'schedule_view/index'

  get 'club_view' => 'club_view#index'
  get 'class_view' => 'class_view#index'
  get 'group_view' => 'group_view#index'

  post 'group_view/index' => 'group_view#index'

  get 'schedule_view' => 'schedule_view#index'

  post 'calendar_events/new' => 'calendar_events#new'

  authenticated :admin do
    root :to => 'user#index', as: :authenticated_root
  end

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

end

ManilaScience/app/models/role.rb
class Role < ActiveRecord::Base
  validates :name, uniqueness: true
  has_many :users
  validates :description,length: { maximum: 50 , too_long: "%{count} characters is the maximum allowed for caption/message" } ,presence: true
end

ManilaScience/app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    if @role.users.length == 0
      @assosciated_users = "None"
    else
      @assosciated_users = @role.users.map(&:username).join(", ")
    end
  end

  # GET /roles/new
  def new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

ManilaScience/app/helpers/roles_helper.rb
module RolesHelper
end

ManilaScience/app/views/roles/_form.html.erb
<div class="ui form segment">
  <%= form_for(@role) do |f| %>
    <% if @role.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

        <ul>
        <% @role.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div class="actions">
      <%= f.submit "Submit", :class => "ui button" %>
    </div>
  <% end %>

</div>

ManilaScience/app/views/roles/edit.html.erb
<h1 class="ui blue header">
  <div data-no-turbolink><%= link_to 'Back', users_path, :class=>"ui right floated button" %></div>
  Editing Role
</h1>

<%= render 'form' %>

ManilaScience/app/views/roles/index.html.erb
<h1 class="ui blue header">
  <%= link_to 'New Role', new_role_path, :class => "ui right floated button" %>
  Roles
</h1>

<table class="ui celled striped selectable table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= role.description %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' }, :class => "ui right floated red button" %>
        <%= link_to 'Edit', edit_role_path(role), :class => "ui right floated blue button" %>
        <%= link_to 'Show', role, :class => "ui right floated green button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

ManilaScience/app/views/roles/new.html.erb
<h1 class="ui blue header">
  <div data-no-turbolink><%= link_to 'Back', users_path, :class=>"ui right floated button" %></div>
  New Role
</h1>

<%= render 'form' %>

ManilaScience/app/views/roles/show.html.erb
<div class="ui blue stacked segment">
  <h2 class="ui blue header">
    <%= link_to 'Back', roles_path, :class => "ui right floated button" %>
    <%= link_to 'Edit', edit_role_path(@role), :class => "ui blue right floated button" %>
    <%= @role.name %>
  </h2>

  <div>
    <%= @role.description %>
  </div>
</div>

<table class="ui celled striped selectable table">
  <thead>
    <tr>
      <th>List of Associated Users</th>
    </tr>
  </thead>

  <tbody>
    <% @role.users.each do |associated_user| %>
      <tr>
        <td>
          <%= associated_user.first_name + " " + associated_user.last_name %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>