ManilaScience/config/routes.rb
Rails.application.routes.draw do

  resources :officers
  get 'class_courses/new_club' => 'class_courses#new_club'

  get 'class_lists/new_view' => 'class_lists#new_view'
  post 'class_lists/new_view' => 'class_lists#new_view'

  post 'class_lists/new_class_lists' => 'class_lists#new_class_lists'

  post 'class_view/view_class' => 'class_view#view_class'
  get 'class_view/view_class' => 'class_view#view_class'

  post 'club_view/view_club' => 'club_view#view_club'
  get 'club_view/view_club' => 'club_view#view_club'

  resources :messages
  resources :thread_message_tables
  resources :thread_messages
  get 'notifications/link_through'

  get 'class_courses/new_club' => 'class_courses#new_club'
  get 'notifications/read_post' => 'notifications#read_post'
  post 'notifications/read_post' => 'notifications#read_post'

  get 'posts/new' => 'posts#new'
  post 'posts/new' => 'posts#new'

  get 'posts/:id' => 'posts#show'
  post 'posts/:id' => 'posts#show'

  get 'posts/:id/edit' => 'posts#edit'
  post 'posts/:id/edit' => 'posts#edit'

  resources :announcements
  resources :posts
  resources :messages
  resources :groups
  resources :group_lists
  resources :posts
  resources :calendar_events

  resources :class_lists
  resources :class_courses
  resources :subjects
  resources :works_ins
  resources :departments
  resources :departments
  resources :employee_lists
  resources :teacher_lists
  resources :notifications
  devise_for :views

  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

  scope "/admin" do
    resources :users
  end

  resources :roles
  resources :users do
    collection { delete :destroy_multiple}
    collection { post :deletebybatch}
    collection { post :import}
    collection do
      delete 'destroy_multiple'
    end
  end

  get 'static/index'

  get 'class_view/index'
  get 'club_view/index'
  get 'group_view/index'
  get 'group_view/edit_student_lists'
  
  post 'group_view/add_user_from_group'
  post 'group_view/remove_user_from_group'

  get 'schedule_view/index'

  get 'club_view' => 'club_view#index'
  get 'class_view' => 'class_view#index'
  get 'group_view' => 'group_view#index'

  post 'group_view/index' => 'group_view#index'

  get 'schedule_view' => 'schedule_view#index'

  post 'calendar_events/new' => 'calendar_events#new'

  authenticated :admin do
    root :to => 'user#index', as: :authenticated_root
  end

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

end

ManilaScience/app/models/message.rb
class Message < ActiveRecord::Base
	#belongs_to :user
	has_many :thread_message_tables ,dependent: :destroy
	validates :author_id, presence: true
	validates :content,presence: true,length: { maximum: 140 , too_long: "%{count} characters is the maximum allowed for message content" }
		
end

ManilaScience/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    @message.author_id = current_user.id

    respond_to do |format|
      if @message.save
        format.html { redirect_to group_view_path, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to group_view_path, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:author_id, :content, :flag, :thread_id)
    end
end

ManilaScience/app/helpers/messages_helper.rb
module MessagesHelper
end

ManilaScience/app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author_id %><br>
    <%= f.number_field :author_id %>
  </div>
  <div class="field">
    <%= f.label :thread_id %><br>
    <%= f.number_field :thread_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :flag %><br>
    <%= f.check_box :flag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ManilaScience/app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

ManilaScience/app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Content</th>
      <th>Flag</th>
      <th>Thread ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.author_id %></td>
        <td><%= message.content %></td>
        <td><%= message.flag %></td>
        <td><%= message.thread_id %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

ManilaScience/app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

ManilaScience/app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @message.author_id %>
</p>

<p>
  <strong>Thread:</strong>
  <%= @message.thread_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>Flag:</strong>
  <%= @message.flag %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>