ManilaScience/config/routes.rb
Rails.application.routes.draw do

  resources :officers
  get 'class_courses/new_club' => 'class_courses#new_club'

  get 'class_lists/new_view' => 'class_lists#new_view'
  post 'class_lists/new_view' => 'class_lists#new_view'

  post 'class_lists/new_class_lists' => 'class_lists#new_class_lists'

  post 'class_view/view_class' => 'class_view#view_class'
  get 'class_view/view_class' => 'class_view#view_class'

  post 'club_view/view_club' => 'club_view#view_club'
  get 'club_view/view_club' => 'club_view#view_club'

  resources :messages
  resources :thread_message_tables
  resources :thread_messages
  get 'notifications/link_through'

  get 'class_courses/new_club' => 'class_courses#new_club'
  get 'notifications/read_post' => 'notifications#read_post'
  post 'notifications/read_post' => 'notifications#read_post'

  get 'posts/new' => 'posts#new'
  post 'posts/new' => 'posts#new'

  get 'posts/:id' => 'posts#show'
  post 'posts/:id' => 'posts#show'

  get 'posts/:id/edit' => 'posts#edit'
  post 'posts/:id/edit' => 'posts#edit'

  resources :announcements
  resources :posts
  resources :messages
  resources :groups
  resources :group_lists
  resources :posts
  resources :calendar_events

  resources :class_lists
  resources :class_courses
  resources :subjects
  resources :works_ins
  resources :departments
  resources :departments
  resources :employee_lists
  resources :teacher_lists
  resources :notifications
  devise_for :views

  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

  scope "/admin" do
    resources :users
  end

  resources :roles
  resources :users do
    collection { delete :destroy_multiple}
    collection { post :deletebybatch}
    collection { post :import}
    collection do
      delete 'destroy_multiple'
    end
  end

  get 'static/index'

  get 'class_view/index'
  get 'club_view/index'
  get 'group_view/index'
  get 'group_view/edit_student_lists'
  
  post 'group_view/add_user_from_group'
  post 'group_view/remove_user_from_group'

  get 'schedule_view/index'

  get 'club_view' => 'club_view#index'
  get 'class_view' => 'class_view#index'
  get 'group_view' => 'group_view#index'

  post 'group_view/index' => 'group_view#index'

  get 'schedule_view' => 'schedule_view#index'

  post 'calendar_events/new' => 'calendar_events#new'

  authenticated :admin do
    root :to => 'user#index', as: :authenticated_root
  end

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

end

ManilaScience/app/controllers/club_view_controller.rb
class ClubViewController < ApplicationController
	def index
		@calendar_events = CalendarEvent.all

		# This is the ClassList Model
		if Role.find(current_user.role_id).name == "Students"
			@clubs_temp = ClassList.where(:user_id => current_user.id)
		else
			@clubs_temp = ClassCourse.where(:teacher_id => current_user.id)
		end
		# 
		for i in (0...@clubs_temp.length)
			@clubs_temp[i] = @clubs_temp[i].attributes
			if Role.find(current_user.role_id).name != "Students"
				@clubs_temp[i]["class_course_id"] = @clubs_temp[i]["id"]
			end
		end
		# We need to find what is the user's section and class adviser

		for i in (0...@clubs_temp.length)
			# We are now joining the ClassList Model to the Course Model
			@course = ClassCourse.find(@clubs_temp[i]["class_course_id"])
			# 
			@clubs_temp[i]["room"] = @course.room
			@clubs_temp[i]["year"] = @course.year
			@clubs_temp[i]["schedule"] = @course.schedule
			@clubs_temp[i]["size"] = @course.size
			@clubs_temp[i]["subject_id"] = @course.subject_id
			# @clubs_temp[i]["created_at"] = @course.created_at
			# @clubs_temp[i]["updated_at"] = @course.updated_at
			@clubs_temp[i]["name"] = @course.name
			@clubs_temp[i]["teacher_id"] = @course.teacher_id
			@clubs_temp[i]["is_club"] = @course.is_club

			# We are now joining the ClassList Model to the Course Model to the Subject
			@subject = Subject.find(@clubs_temp[i]["subject_id"])
			@clubs_temp[i]["subject_name"] = @subject.subject_name
			@clubs_temp[i]["offered"] = @subject.offered
			@clubs_temp[i]["department_id"] = @subject.department_id

			# @clubs_temp[i]["subj_created_at"] = @subject.created_at
			# @clubs_temp[i]["subj_updated_at"] = @subject.created_at

		end

		@clubs = Array.new
		for i in (0...@clubs_temp.length)
			if @clubs_temp[i]["is_club"] == true
				@clubs.append(@clubs_temp[i])
			end
		end
	end

	def view_club
		
		@id = params[:class_course_id]
		@class_course = ClassCourse.find_by_id(@id)
		@subject = Subject.all
		@users = User.all
		@classes_lists = ClassList.where(:class_course_id => @id)
		@posts = Post.where(:class_course_id => @id)

		#
	end
end

ManilaScience/app/helpers/club_view_helper.rb
module ClubViewHelper
end

ManilaScience/app/views/club_view/index.html.erb
<h2 class="ui blue header" id="pc">Club Calendar</h2>
<% if @calendar_events == [] %>
  <%= month_calendar do |date| %>
    <%= date.day %>
  <% end %>
<% else %>
  <%= month_calendar events:@calendar_events, attribute: :start_time do |date, calendar_events| %>
    <%= date.day %>
    <% calendar_events.each do |calendar_event| %>
			<% if calendar_event.event_type == "class" %>
	      <div>
	        <%= calendar_event.title %>
	      </div>
			<% end %>
    <% end %>
  <% end %>
<% end %>

<h2 class="ui blue header">
  List of Clubs
</h2>
<div class="ui blue stacked segment">
  <% @clubs.each do |c| %>
    <%= button_to "View", club_view_view_club_path, params: { class_course_id: c["class_course_id"].to_s }, :class => "ui green right floated button" %>
    <%= c["name"] + " " + c["subject_name"] %>
    <div class="ui blue divider"></div>
  <% end %>
</div>

ManilaScience/app/views/club_view/view_club.html.erb
<h1 class="ui blue header">
  <%= link_to 'Back', club_view_path, 'data-no-turbolink' => true, :class => "ui right floated button" %>
  <% if Role.find(current_user.role_id.to_s).name != "Students" %>
    <%= link_to 'Edit', edit_class_course_path(@class_course), :class => "ui blue right floated button" %>
  <% end %>
  <%= @class_course.name + " " + @class_course.subject.subject_name %>
</h1>

<div class="ui blue stacked segment">
  <h3 class="ui blue header">
    Details
  </h3>
  <p>
    <strong>Id: </strong><%= @class_course.id %><br>
    <% if @class_course.year != 7 %>
      <strong>Year: </strong><%= @class_course.year %><br>
    <% end %>
    <strong>Teacher: </strong><%= @class_course.teacher_id.nil? ? "None" : User.find(@class_course.teacher_id).first_name.to_s + " " + User.find(@class_course.teacher_id).last_name.to_s  %><br>
    <strong>Schedule: </strong><%= @class_course.schedule %><br>
    <strong>Room: </strong><%= @class_course.room %><br>
    <strong>Size: </strong><%= @class_course.size %>
  </p>
</div>

<h2 class="ui blue header">
  <% if Role.find(current_user.role_id.to_s).name != "Students" %>
    <%= button_to 'New Announcement', posts_new_path, params: { id: @class_course.id.to_s, :announcement => "true" } , :class => "ui right floated button"%>
  <% end %>
  Announcements
</h2>
<div class="ui blue stacked segment">
  <% @posts.each do |post| %>
    <% if post.document_file_name == nil %>
      <% if Role.find(current_user.role_id.to_s).name != "Students" %>
        <%= button_to 'Delete', post_path(:id => post.id, :course_id => params[:id].to_s), method: :delete, data: {confirm: 'Are you sure?'}, :class => "ui red right floated button" %>
        <%= button_to 'Edit', edit_post_path(post), params: { course_id: params[:id].to_s }, :class => "ui blue right floated button" %>
        <%= button_to 'Show', post, params: { course_id: params[:id].to_s }, :class => "ui green right floated button" %>
      <% end %>
      <p>
        <%= post.caption %>
      </p>
      <div class="ui blue divider"></div>
    <% end %>
  <% end %>
</div>

<h2 class="ui blue header">
  <% if Role.find(current_user.role_id.to_s).name != "Students" %>
    <%= button_to 'New Post', posts_new_path, params: { id: @class_course.id.to_s, :announcement => "false" } , :class => "ui right floated button"%>
  <% end %>
  Posts
</h2>

<div class="ui blue stacked segment">
  <% @posts.each do |post| %>
    <% if post.document_file_name != nil %>
      <% if Role.find(current_user.role_id.to_s).name != "Students" %>
        <%= button_to 'Delete', post_path(:id => post.id, :course_id => params[:id].to_s), method: :delete, data: {confirm: 'Are you sure?'}, :class => "ui red right floated button" %>
        <%= button_to 'Edit', edit_post_path(post), params: { course_id: params[:id].to_s }, :class => "ui blue right floated button" %>
        <%= button_to 'Show', post, params: { course_id: params[:id].to_s }, :class => "ui green right floated button" %>
      <% else %>
        <%= link_to "View", post.document.url(:original, false), :class => "ui green right floated button" %>
      <% end %>
      <p>
        <%= post.caption %>
      </p>
      <div class="ui blue divider"></div>
    <% end %>
  <% end %>
</div>