ManilaScience/config/routes.rb
Rails.application.routes.draw do

  resources :officers
  get 'class_courses/new_club' => 'class_courses#new_club'

  get 'class_lists/new_view' => 'class_lists#new_view'
  post 'class_lists/new_view' => 'class_lists#new_view'

  post 'class_lists/new_class_lists' => 'class_lists#new_class_lists'

  post 'class_view/view_class' => 'class_view#view_class'
  get 'class_view/view_class' => 'class_view#view_class'

  post 'club_view/view_club' => 'club_view#view_club'
  get 'club_view/view_club' => 'club_view#view_club'

  resources :messages
  resources :thread_message_tables
  resources :thread_messages
  get 'notifications/link_through'

  get 'class_courses/new_club' => 'class_courses#new_club'
  get 'notifications/read_post' => 'notifications#read_post'
  post 'notifications/read_post' => 'notifications#read_post'

  get 'posts/new' => 'posts#new'
  post 'posts/new' => 'posts#new'

  get 'posts/:id' => 'posts#show'
  post 'posts/:id' => 'posts#show'

  get 'posts/:id/edit' => 'posts#edit'
  post 'posts/:id/edit' => 'posts#edit'

  resources :announcements
  resources :posts
  resources :messages
  resources :groups
  resources :group_lists
  resources :posts
  resources :calendar_events

  resources :class_lists
  resources :class_courses
  resources :subjects
  resources :works_ins
  resources :departments
  resources :departments
  resources :employee_lists
  resources :teacher_lists
  resources :notifications
  devise_for :views

  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

  scope "/admin" do
    resources :users
  end

  resources :roles
  resources :users do
    collection { delete :destroy_multiple}
    collection { post :deletebybatch}
    collection { post :import}
    collection do
      delete 'destroy_multiple'
    end
  end

  get 'static/index'

  get 'class_view/index'
  get 'club_view/index'
  get 'group_view/index'
  get 'group_view/edit_student_lists'
  
  post 'group_view/add_user_from_group'
  post 'group_view/remove_user_from_group'

  get 'schedule_view/index'

  get 'club_view' => 'club_view#index'
  get 'class_view' => 'class_view#index'
  get 'group_view' => 'group_view#index'

  post 'group_view/index' => 'group_view#index'

  get 'schedule_view' => 'schedule_view#index'

  post 'calendar_events/new' => 'calendar_events#new'

  authenticated :admin do
    root :to => 'user#index', as: :authenticated_root
  end

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

end

ManilaScience/app/controllers/class_courses_controller.rb
class ClassCoursesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
#  before_filter :authenticate_user!
#  before_action :set_class_course, only: [:show, :edit, :update, :destroy]

  # GET /class_courses
  # GET /class_courses.json
  def index
    @class_courses = ClassCourse.all
    @subjects = Subject.all
  end

  # GET /class_courses/1
  # GET /class_courses/1.json
  def show
    @id = params[:id]
    @subject = Subject.all
    @users = User.all
    @classes_lists = ClassList.where(:class_course_id => @id)
    @posts = Post.where(:class_course_id => @id)
  end

  # GET /class_courses/new
  def new
    @class_course = ClassCourse.new
    session[:is_club] = false
  end

  def new_club
    @class_course = ClassCourse.new
    session[:is_club] = true
  end

  # GET /class_courses/1/edit
  def edit
  end

  # POST /class_courses
  # POST /class_courses.json
  def create
    @class_course = ClassCourse.new(class_course_params)
    @class_course.subject_id = params[:subject_id][:subject_id]
    @class_course.teacher_id = params[:teacher_id][:id]
    @class_course.is_club = session[:is_club]

    days = ""
    schedule = params[:class_course][:schedule]
    days_abbrev = ["M", "T", "W", "TH", "F", "SA", "SU"]
    days_abbrev.each do |d|
      if schedule.include? d
        days = days + d
      end
    end

    @class_course.schedule = days + " " + params[:start_time] + "-" + params[:end_time]
    @class_course.name = @class_course.year.to_s + params[:section]

    respond_to do |format|
      if @class_course.save
        session[:is_club] = nil
        format.html { redirect_to @class_course, notice: 'Class/Club was successfully created.' }
        format.json { render :show, status: :created, location: @class_course }
      else
        format.html { render :new }
        format.json { render json: @class_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /class_courses/1
  # PATCH/PUT /class_courses/1.json
  def update
    @class_course.subject_id = params[:subject_id][:subject_id]
    @class_course.teacher_id = params[:teacher_id][:id]

    days = ""
    schedule = params[:class_course][:schedule]
    days_abbrev = ["M", "T", "W", "TH", "F", "SA", "SU"]
    days_abbrev.each do |d|
      if schedule.include? d
        days = days + d
      end
    end

    @class_course.schedule = days + " " + params[:start_time] + "-" + params[:end_time]
    @class_course.name = @class_course.year.to_s + "-" + params[:section]

    respond_to do |format|
      if @class_course.update(class_course_params)
        format.html { redirect_to @class_course, notice: 'Class course was successfully updated.' }
        format.json { render :show, status: :ok, location: @class_course }
      else
        format.html { render :edit }
        format.json { render json: @class_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_courses/1
  # DELETE /class_courses/1.json
  def destroy
    Group.where(class_id:@class_course.id).delete_all()     #delete all groups inside that class
    ClassList.where(class_course_id:@class_course.id).delete_all() #delete all the related class_list to it
    @class_course.destroy
    respond_to do |format|
      format.html { redirect_to class_courses_url, notice: 'Class course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class_course
      @class_course = ClassCourse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def class_course_params
      params.require(:class_course).permit(:name, :room, :year, :schedule, :size, :subject_id, :new, :teacher_id, :is_club)
    end
end

ManilaScience/app/helpers/class_courses_helper.rb
module ClassCoursesHelper
end

ManilaScience/app/views/class_courses/_form.html.erb
<div class="ui blue form segment">
  <%= form_for(@class_course) do |f| %>
    <% if @class_course.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@class_course.errors.count, "error") %> prohibited this class_course from being saved:</h2>

        <ul>
        <% @class_course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="two fields">
      <div class="field">
        <%= f.label :year %>
        <%= f.select(:year, [['First Year', 1], ['Second Year', 2], ['Third Year', 3], ['Fourth Year', 4], ['Fifth Year', 5], ['Sixth Year', 6],['NA (Club)', 7]],
         {:prompt => true}, {:class => "ui selection dropdown"}) %>
      </div>
      
      <div class="field">
        <%= f.label :section %>
        <%= text_field_tag :section %>
      </div>
    </div>

    <div class="two fields">
      <div class="field">
        <%= f.label :subject_id %>
        <%= collection_select(:subject_id, :subject_id, Subject.all, :id, :subject_name, {prompt: true}, {:class => "ui selection dropdown"}) %>
      </div>

      <div class="field">
        <%= f.label :teacher_id %>
        <% our_number = Role.where(name: "Teacher") %>
        <%= collection_select(:teacher_id, :id, User.all.where(role_id: our_number), :id, :last_name, {prompt: true}, {:class => "ui selection dropdown", :required => true}) %>
      </div>
    </div>

    <div class="three fields">
      <div class="field">
        <%= f.label :schedule %>
        <%= f.select(:schedule, [['M', 'M'], ['T', 'T'], ['W', 'W'], ['TH', 'TH'], ['F', 'F'], ['SA', 'SA'], ['SU', 'SU']], {:prompt => true}, { :multiple => "", :class => "ui selection dropdown" }) %>
      </div>

      <div class="field">
        <%= f.label :start_time %>
        <%= time_field_tag :start_time %>
      </div>

      <div class="field">
        <%= f.label :end_time %>
        <%= time_field_tag :end_time %>
      </div>
    </div>


    <div class="two fields">
      <div class="field">
        <%= f.label :room %>
        <%= f.text_field :room %>
      </div>

      <div class="field">
        <%= f.label :size %>
        <%= f.number_field :size %>
      </div>
    </div>

    <div class="actions">
      <%= f.submit "Submit", :class => "ui button" %>
    </div>
  <% end %>
</div>

ManilaScience/app/views/class_courses/edit.html.erb
<h1 class="ui blue header">
  <%= link_to 'Back', class_courses_path, :class => "ui right floated button", 'data-no-turbolink' => true %>
  Edit Class/Club Details
</h1>

<%= render 'form' %>

ManilaScience/app/views/class_courses/index.html.erb
<h1 class="ui blue header">
  <%= link_to 'New Class', new_class_course_path, :class => "ui right floated button", 'data-no-turbolink' => true %>
  Classes
</h1>
<div class="ui styled fluid accordion">
  <% years = ["", "First", "Second", "Third", "Fourth", "Fifth", "Sixth"] %>
  <% for i in 1..6 %>
    <div class="title">
      <i class="dropdown icon"></i>
      <%= years[i] %>
    </div>
    <div class="content">
      <div class="ui segment">
        <% @class_courses.each do |class_course| %>
          <% if class_course.is_club == false && class_course.year == i %>
            <%= link_to 'Destroy', class_course, method: :delete, data: { confirm: 'Are you sure?' }, :class => "ui right floated red button" %>
            <%= link_to 'Edit', edit_class_course_path(class_course), :class => "ui right floated blue button", 'data-no-turbolink' => true %>
            <%= link_to 'Show', class_course, :class => "ui right floated green button" %>
            <p>
              <%= class_course.name + " " + @subjects.find(class_course.subject_id).subject_name %>
            </p>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<h1 class="ui blue header">
  <%= link_to 'New Club', class_courses_new_club_path, :class => "ui right floated button", 'data-no-turbolink' => true %>
  Clubs
</h1>

<table class="ui celled striped table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @class_courses.each do |class_course| %>
      <% if class_course.is_club == true %>
        <tr>
          <td><%= class_course.name + " " + @subjects.find(class_course.subject_id).subject_name %></td>
          <td><%= class_course.teacher_id.nil? ? "None" : User.find(class_course.teacher_id).first_name.to_s + " " + User.find(class_course.teacher_id).last_name.to_s %>
          </td>

          <td><%= link_to 'Destroy', class_course, method: :delete, data: { confirm: 'Are you sure?' }, :class => "ui right floated red button" %>
          <%= link_to 'Edit', edit_class_course_path(class_course), :class => "ui right floated blue button", 'data-no-turbolink' => true %>
          <%= link_to 'Show', class_course, :class => "ui right floated green button" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

ManilaScience/app/views/class_courses/new.html.erb
<h1 class="ui blue header">
  <%= link_to 'Back', class_courses_path, :class=>"ui right floated button", 'data-no-turbolink' => true %>
  New Class
</h1>

<%= render 'form' %>

ManilaScience/app/views/class_courses/new_club.html.erb
<h1 class="ui blue header">
  <%= link_to 'Back', class_courses_path, :class=>"ui right floated button" %>
  New Club
</h1>

<%= render 'form' %>

ManilaScience/app/views/class_courses/show.html.erb
<h1 class="ui blue header">
  <%= link_to 'Back', class_courses_path, 'data-no-turbolink' => true, :class => "ui right floated button" %>
  <%= link_to 'Edit', edit_class_course_path(@class_course), :class => "ui blue right floated button", "data-no-turbolink": true %>
  <%= @class_course.name + " " + @class_course.subject.subject_name %>
</h1>

<div class="ui blue stacked segment">
  <h3 class="ui blue header">
    Details
  </h3>
  <p>
    <strong>Id: </strong><%= @class_course.id %><br>
    <% if @class_course.year != 7 %>
      <strong>Year: </strong><%= @class_course.year %><br>
    <% end %>
    <strong>Teacher: </strong><%= @class_course.teacher_id.nil? ? "None" : User.find(@class_course.teacher_id).first_name.to_s + " " + User.find(@class_course.teacher_id).last_name.to_s  %><br>
    <strong>Schedule: </strong><%= @class_course.schedule %><br>
    <strong>Room: </strong><%= @class_course.room %><br>
    <strong>Size: </strong><%= @class_course.size %>
  </p>
</div>

<h2 class="ui blue header">
  <%= button_to 'Edit List', class_lists_new_view_path, params: { class_course_id: params[:id].to_s } , :class => "ui blue right floated button"%>
  List of Students
</h2>

<div class="ui blue stacked segment">
  <% @classes_lists.each do |classes_list| %>
    <%= link_to 'Delete', classes_list, method: :delete, data: { confirm: 'Are you sure?' }, :class => "ui right floated red button" %>
    <p>
      <%= classes_list.user.name + " (" + classes_list.status + ")"%>
    </p>
    <div class="ui blue divider"></div>
  <% end %>
</div>

<h2 class="ui blue header">
  <%= button_to 'New Announcement', posts_new_path, params: { id: params[:id].to_s, :announcement => "true" } , :class => "ui right floated button"%>
  Announcements
</h2>
<div class="ui blue stacked segment">
  <% @posts.each do |post| %>
    <% if post.document_file_name == nil %>
      <%= button_to 'Delete', post_path(:id => post.id, :course_id => params[:id].to_s), method: :delete, data: {confirm: 'Are you sure?'}, :class => "ui red right floated button" %>
      <%= button_to 'Edit', edit_post_path(post), params: { course_id: params[:id].to_s }, :class => "ui blue right floated button" %>
      <%= button_to 'Show', post, params: { course_id: params[:id].to_s }, :class => "ui green right floated button" %>
      <p>
        <%= post.caption %>
      </p>
      <div class="ui blue divider"></div>
    <% end %>
  <% end %>
</div>

<h2 class="ui blue header">
  <%= button_to 'New Post', posts_new_path, params: { id: params[:id].to_s, :announcement => "false" } , :class => "ui right floated button"%>
  Posts
</h2>

<div class="ui blue stacked segment">
  <% @posts.each do |post| %>
    <% if post.document_file_name != nil %>
      <%= button_to 'Delete', post_path(:id => post.id, :course_id => params[:id].to_s), method: :delete, data: {confirm: 'Are you sure?'}, :class => "ui red right floated button" %>
      <%= button_to 'Edit', edit_post_path(post), params: { course_id: params[:id].to_s }, :class => "ui blue right floated button" %>
      <%= button_to 'Show', post, params: { course_id: params[:id].to_s }, :class => "ui green right floated button" %>
      <p>
        <%= post.caption %>
      </p>
      <div class="ui blue divider"></div>
    <% end %>
  <% end %>
</div>